import 'dart:async';
import 'dart:convert';

import 'package:flutter/foundation.dart';
import 'package:http/http.dart' as http;

import '../models/capture_session.dart';

/// Handles all HTTP communication with the backend server.
///
/// ApiService is ONLY responsible for network I/O. It does NOT:
/// - delete sessions or modify SQLite
/// - mark sessions synced/pending
/// - retry requests or listen for connectivity
/// - show UI, SnackBars, or navigation
///
/// SyncService (Step 3.2) owns offline-sync orchestration.
class ApiService {
  /// Where the backend lives when nothing has overridden it: the Android
  /// emulator's loopback alias for the host machine.
  static const String defaultBaseUrl = 'http://10.0.2.2:8000';

  /// Base URL for the backend server.
  ///
  /// A var, not a const, because a demo on a physical handset needs to point
  /// at a laptop on the same Wi-Fi and there is no way to rebuild the app in
  /// the field. Settings writes it, [DbService] persists it, and
  /// [SettingsService.restore] reloads it before the first request.
  static String baseUrl = defaultBaseUrl;

  /// Timeout for simple GET requests.
  static const Duration _requestTimeout = Duration(seconds: 15);

  /// Timeout for multipart uploads (media files can be large).
  static const Duration _uploadTimeout = Duration(seconds: 120);

  /// Timeout for a chat reply. The answer is generated by a model running
  /// on the host, which is slower than any other call the app makes.
  static const Duration _chatTimeout = Duration(seconds: 120);

  /// Headers sent with every request.
  static const Map<String, String> _jsonHeaders = {
    'Accept': 'application/json',
  };

  final http.Client _client;

  /// Creates an [ApiService] with an optional custom [http.Client].
  ApiService({http.Client? client}) : _client = client ?? http.Client();

  /// Releases the underlying HTTP client.
  void close() {
    _client.close();
  }

  /// Fetches animal details for the given tag [id].
  ///
  /// GET /animal/{id}
  ///
  /// Returns the decoded JSON map on success.
  /// On any failure (network, timeout, non-2xx, malformed JSON),
  /// returns a map containing an `error` key with a description.
  Future<Map<String, dynamic>> getAnimal(String id) {
    return _getJson('/animal/${Uri.encodeComponent(id)}', 'getAnimal');
  }

  /// Fetches the history for the given tag [id].
  ///
  /// GET /animal/{id}/history
  ///
  /// Returns the decoded JSON map on success.
  /// On any failure, returns a map containing an `error` key.
  Future<Map<String, dynamic>> getHistory(String id) {
    return _getJson('/animal/${Uri.encodeComponent(id)}/history', 'getHistory');
  }

  /// Uploads a capture [session] to the backend as multipart/form-data.
  ///
  /// POST /session
  ///
  /// Sends the tag ID, side photo, rear photo, and video using the paths
  /// already stored in [CaptureSession]. Files are read in place and are
  /// never copied or moved.
  ///
  /// Returns the decoded JSON response map on HTTP 2xx.
  /// Returns `null` on ANY failure: network error, timeout, missing file,
  /// non-2xx response, or malformed response body.
  Future<Map<String, dynamic>?> uploadSession(CaptureSession session) async {
    final tagId = session.tagId;
    final sidePhotoPath = session.sidePhotoPath;
    final rearPhotoPath = session.rearPhotoPath;
    final videoPath = session.videoPath;

    if (tagId == null || tagId.isEmpty) {
      debugPrint('ApiService.uploadSession: missing tag ID');
      return null;
    }
    if (sidePhotoPath == null ||
        sidePhotoPath.isEmpty ||
        rearPhotoPath == null ||
        rearPhotoPath.isEmpty ||
        videoPath == null ||
        videoPath.isEmpty) {
      debugPrint('ApiService.uploadSession: missing media path');
      return null;
    }

    final uri = Uri.parse('$baseUrl/session');
    final request = http.MultipartRequest('POST', uri);
    request.headers.addAll(_jsonHeaders);
    request.fields['tag_id'] = tagId;

    try {
      request.files.add(
        await http.MultipartFile.fromPath('side_photo', sidePhotoPath),
      );
      request.files.add(
        await http.MultipartFile.fromPath('rear_photo', rearPhotoPath),
      );
      request.files.add(await http.MultipartFile.fromPath('video', videoPath));

      // Optional, and deliberately not part of the required-path check above:
      // a session without a tag close-up still uploads and still scores its
      // angle traits. The server accepts either 'tag_photo' or 'tag_image'.
      final tagPhotoPath = session.tagPhotoPath;
      if (tagPhotoPath != null && tagPhotoPath.isNotEmpty) {
        request.files.add(
          await http.MultipartFile.fromPath('tag_photo', tagPhotoPath),
        );
      }
    } catch (e) {
      debugPrint('ApiService.uploadSession: failed to attach media: $e');
      return null;
    }

    try {
      final streamedResponse = await _client
          .send(request)
          .timeout(_uploadTimeout);
      final response = await http.Response.fromStream(streamedResponse);

      if (response.statusCode < 200 || response.statusCode >= 300) {
        debugPrint(
          'ApiService.uploadSession failed with status ${response.statusCode}',
        );
        return null;
      }

      return _decodeJson(response.body);
    } on TimeoutException {
      debugPrint('ApiService.uploadSession timed out');
      return null;
    } catch (e) {
      debugPrint('ApiService.uploadSession failed: $e');
      return null;
    }
  }

  /// Lists every animal in the BPA records.
  ///
  /// GET /animals
  Future<Map<String, dynamic>> getAnimals() {
    return _getJson('/animals', 'getAnimals');
  }

  /// Fetches the veterinary officer's escalation feed.
  ///
  /// GET /alerts
  Future<Map<String, dynamic>> getAlerts() {
    return _getJson('/alerts', 'getAlerts');
  }

  /// Fetches one stored scorecard by session ID.
  ///
  /// GET /session/{id}
  Future<Map<String, dynamic>> getSession(String sessionId) {
    return _getJson('/session/${Uri.encodeComponent(sessionId)}', 'getSession');
  }

  /// Checks that the server is reachable and reports what it can do.
  ///
  /// GET /ping. Short timeout: this backs a "test connection" button, and a
  /// farmer tapping it wants an answer, not fifteen seconds of spinner.
  Future<Map<String, dynamic>> ping() async {
    final uri = Uri.parse('$baseUrl/ping');
    try {
      final response = await _client
          .get(uri, headers: _jsonHeaders)
          .timeout(const Duration(seconds: 6));
      if (response.statusCode != 200) {
        return _errorMap('server answered ${response.statusCode}');
      }
      return _decodeJson(response.body) ?? _errorMap('malformed reply');
    } on TimeoutException {
      return _errorMap('no reply within 6s');
    } catch (e) {
      return _errorMap('$e');
    }
  }

  /// Asks a question about ONE animal, answered from its record alone.
  ///
  /// POST /chat
  ///
  /// [language] is `auto`, `en`, `hi` or `kn`; `auto` lets the server detect
  /// the language of [message] and reply in kind.
  ///
  /// The reply can take a while - the model runs locally on the host - so this
  /// gets its own generous timeout rather than the shared GET one.
  Future<Map<String, dynamic>> chat(
    String animalId,
    String message, {
    String language = 'auto',
    bool speak = false,
  }) async {
    final uri = Uri.parse('$baseUrl/chat');
    try {
      final response = await _client
          .post(
            uri,
            headers: const {
              'Accept': 'application/json',
              'Content-Type': 'application/json',
            },
            body: jsonEncode({
              'animal_id': animalId,
              'message': message,
              'language': language,
              'speak': speak,
            }),
          )
          .timeout(_chatTimeout);

      if (response.statusCode == 404) {
        return _errorMap('That animal is not in the BPA records.');
      }
      if (response.statusCode < 200 || response.statusCode >= 300) {
        return _errorMap('Assistant unavailable (${response.statusCode}).');
      }
      return _decodeJson(response.body) ??
          _errorMap('Assistant sent a reply this app could not read.');
    } on TimeoutException {
      return _errorMap('The assistant took too long to answer.');
    } catch (e) {
      return _errorMap('Could not reach the assistant: $e');
    }
  }

  /// Performs a GET request and decodes the JSON response.
  Future<Map<String, dynamic>> _getJson(String path, String operation) async {
    final uri = Uri.parse('$baseUrl$path');
    try {
      final response = await _client
          .get(uri, headers: _jsonHeaders)
          .timeout(_requestTimeout);

      if (response.statusCode < 200 || response.statusCode >= 300) {
        return _errorMap(
          '$operation failed with status ${response.statusCode}',
        );
      }

      final decoded = _decodeJson(response.body);
      if (decoded == null) {
        return _errorMap('$operation failed: malformed JSON response');
      }
      return decoded;
    } on TimeoutException {
      return _errorMap('$operation timed out');
    } catch (e) {
      return _errorMap('$operation failed: $e');
    }
  }

  /// Decodes a JSON object body into a map, or `null` if malformed.
  Map<String, dynamic>? _decodeJson(String body) {
    try {
      final decoded = jsonDecode(body);
      if (decoded is Map<String, dynamic>) {
        return decoded;
      }
      debugPrint('ApiService: response was not a JSON object');
      return null;
    } catch (e) {
      debugPrint('ApiService: malformed JSON response: $e');
      return null;
    }
  }

  /// Builds a failure map with an `error` key.
  Map<String, dynamic> _errorMap(String message) => {'error': message};
}
