"""Trait registry: authoritative list of NDDB-style type traits and lookup helpers."""

TRAIT_REGISTRY = [
    # ---------------- Class A: angles (degrees) ----------------
    {
        "trait_id": "rump_angle",
        "name": "Rump Angle",
        "trait_class": "A",
        "required_keypoints": ["hook_left", "pin_left", "hook_right", "pin_right"],
        "required_scale": False,
        "unit": "degrees",
        "smal_fallback": True,
        "species_variants": ["cattle", "buffalo"],
    },
    {
        "trait_id": "hock_angle",
        "name": "Hock Angle",
        "trait_class": "A",
        "required_keypoints": ["knee_left", "hock_left", "pastern_left"],
        "required_scale": False,
        "unit": "degrees",
        "smal_fallback": True,
        "species_variants": ["cattle", "buffalo"],
    },
    {
        "trait_id": "pastern_angle",
        "name": "Pastern (Foot) Angle",
        "trait_class": "A",
        "required_keypoints": ["hock_left", "pastern_left", "hoof_left"],
        "required_scale": False,
        "unit": "degrees",
        "smal_fallback": True,
        "species_variants": ["cattle", "buffalo"],
    },
    {
        "trait_id": "rear_leg_set",
        "name": "Rear Leg Set",
        "trait_class": "A",
        "required_keypoints": ["hip_bone_left", "hip_bone_right", "hock_left", "hock_right"],
        "required_scale": False,
        "unit": "degrees",
        "smal_fallback": True,
        "species_variants": ["cattle", "buffalo"],
    },
    {
        "trait_id": "fore_leg_set",
        "name": "Fore Leg Set",
        "trait_class": "A",
        "required_keypoints": ["shoulder_left", "shoulder_right", "hoof_left", "hoof_right"],
        "required_scale": False,
        "unit": "degrees",
        "smal_fallback": True,
        "species_variants": ["cattle", "buffalo"],
    },
    {
        "trait_id": "shoulder_angle",
        "name": "Shoulder Angle",
        "trait_class": "A",
        "required_keypoints": ["withers", "shoulder_left", "chest_front"],
        "required_scale": False,
        "unit": "degrees",
        "smal_fallback": True,
        "species_variants": ["cattle", "buffalo"],
    },
    # ---------------- Class B: ratios (dimensionless) ----------------
    {
        "trait_id": "body_length_to_height_ratio",
        "name": "Body Length to Height Ratio",
        "trait_class": "B",
        "required_keypoints": ["chest_front", "pin_left", "withers", "hoof_left"],
        "required_scale": False,
        "unit": "ratio",
        "smal_fallback": True,
        "species_variants": ["cattle", "buffalo"],
    },
    {
        "trait_id": "chest_width_to_depth_ratio",
        "name": "Chest Width to Depth Ratio",
        "trait_class": "B",
        "required_keypoints": ["chest_width_left", "chest_width_right", "withers", "chest_bottom"],
        "required_scale": False,
        "unit": "ratio",
        "smal_fallback": True,
        "species_variants": ["cattle", "buffalo"],
    },
    {
        "trait_id": "topline_symmetry",
        "name": "Topline Symmetry",
        "trait_class": "B",
        "required_keypoints": ["withers", "back_mid", "hook_left", "pin_left"],
        "required_scale": False,
        "unit": "ratio",
        "smal_fallback": True,
        "species_variants": ["cattle", "buffalo"],
    },
    {
        "trait_id": "pin_width_to_hook_distance_ratio",
        "name": "Pin Width to Hook Distance Ratio",
        "trait_class": "B",
        "required_keypoints": ["hook_left", "hook_right", "pin_left", "pin_right"],
        "required_scale": False,
        "unit": "ratio",
        "smal_fallback": True,
        "species_variants": ["cattle", "buffalo"],
    },
    {
        "trait_id": "udder_depth_ratio",
        "name": "Udder Depth Ratio",
        "trait_class": "B",
        "required_keypoints": ["rear_udder", "hock_left", "hock_right", "hoof_right"],
        "required_scale": False,
        "unit": "ratio",
        "smal_fallback": True,
        "species_variants": ["cattle", "buffalo"],
    },
    {
        "trait_id": "body_width_to_length_ratio",
        "name": "Body Width to Length Ratio",
        "trait_class": "B",
        "required_keypoints": ["chest_width_left", "chest_width_right", "chest_front", "pin_left"],
        "required_scale": False,
        "unit": "ratio",
        "smal_fallback": True,
        "species_variants": ["cattle", "buffalo"],
    },
    # ---------------- Class C: direct measurements (cm) ----------------
    {
        "trait_id": "heart_girth",
        "name": "Heart Girth",
        "trait_class": "C",
        "required_keypoints": ["withers", "chest_bottom"],
        "required_scale": True,
        "unit": "cm",
        "smal_fallback": True,
        # NOTE: 2D value is a chest-depth proxy, not true girth circumference.
        # Prefer the SMAL-mesh fallback for heart_girth whenever a fit is available.
        "species_variants": ["cattle", "buffalo"],
    },
    {
        "trait_id": "body_length",
        "name": "Body Length",
        "trait_class": "C",
        "required_keypoints": ["chest_front", "pin_right"],
        "required_scale": True,
        "unit": "cm",
        "smal_fallback": True,
        "species_variants": ["cattle", "buffalo"],
    },
    {
        "trait_id": "height_at_withers",
        "name": "Height at Withers",
        "trait_class": "C",
        "required_keypoints": ["withers", "hoof_left"],
        "required_scale": True,
        "unit": "cm",
        "smal_fallback": True,
        "species_variants": ["cattle", "buffalo"],
    },
    {
        "trait_id": "rump_length",
        "name": "Rump Length",
        "trait_class": "C",
        "required_keypoints": ["hook_left", "pin_left"],
        "required_scale": True,
        "unit": "cm",
        "smal_fallback": True,
        "species_variants": ["cattle", "buffalo"],
    },
    {
        "trait_id": "chest_width",
        "name": "Chest Width",
        "trait_class": "C",
        "required_keypoints": ["chest_width_left", "chest_width_right"],
        "required_scale": True,
        "unit": "cm",
        "smal_fallback": True,
        "species_variants": ["cattle", "buffalo"],
    },
    {
        "trait_id": "chest_depth",
        "name": "Chest Depth",
        "trait_class": "C",
        "required_keypoints": ["withers", "chest_bottom"],
        "required_scale": True,
        "unit": "cm",
        "smal_fallback": True,
        "species_variants": ["cattle", "buffalo"],
    },
    {
        "trait_id": "rump_width",
        "name": "Rump Width",
        "trait_class": "C",
        "required_keypoints": ["hook_left", "hook_right"],
        "required_scale": True,
        "unit": "cm",
        "smal_fallback": True,
        "species_variants": ["cattle", "buffalo"],
    },
    {
        "trait_id": "udder_depth",
        "name": "Udder Depth",
        "trait_class": "C",
        "required_keypoints": ["rear_udder", "hock_left"],
        "required_scale": True,
        "unit": "cm",
        "smal_fallback": True,
        "species_variants": ["cattle", "buffalo"],
    },
]


def get_trait(trait_id: str) -> dict:
    """Return the registry entry for a single trait id."""
    for trait in TRAIT_REGISTRY:
        if trait["trait_id"] == trait_id:
            return trait
    raise KeyError(f"Unknown trait_id: {trait_id!r}")


def get_traits_by_class(trait_class: str) -> list:
    """Return all registry entries belonging to the given trait class (A, B, or C)."""
    return [trait for trait in TRAIT_REGISTRY if trait["trait_class"] == trait_class]